// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0HD39vHGkbwNZ5B5zjspxOo8yqNuXag',
    appId: '1:352135072721:web:b91c83a9743191de202ef0',
    messagingSenderId: '352135072721',
    projectId: 'diagnosticos-fritzcell',
    authDomain: 'diagnosticos-fritzcell.firebaseapp.com',
    storageBucket: 'diagnosticos-fritzcell.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXAvx0vX3abWyUIhWhAjhWfD_kBoa9yqw',
    appId: '1:352135072721:android:ca99bb0e8d4a6361202ef0',
    messagingSenderId: '352135072721',
    projectId: 'diagnosticos-fritzcell',
    storageBucket: 'diagnosticos-fritzcell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIHsKhBmZlxw-K9VoJcOenY2PzZgQNHOM',
    appId: '1:352135072721:ios:fa21d75b1ce791e9202ef0',
    messagingSenderId: '352135072721',
    projectId: 'diagnosticos-fritzcell',
    storageBucket: 'diagnosticos-fritzcell.firebasestorage.app',
    iosBundleId: 'com.example.fritzcell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIHsKhBmZlxw-K9VoJcOenY2PzZgQNHOM',
    appId: '1:352135072721:ios:fa21d75b1ce791e9202ef0',
    messagingSenderId: '352135072721',
    projectId: 'diagnosticos-fritzcell',
    storageBucket: 'diagnosticos-fritzcell.firebasestorage.app',
    iosBundleId: 'com.example.fritzcell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu0HD39vHGkbwNZ5B5zjspxOo8yqNuXag',
    appId: '1:352135072721:web:d84e8791383d4b1c202ef0',
    messagingSenderId: '352135072721',
    projectId: 'diagnosticos-fritzcell',
    authDomain: 'diagnosticos-fritzcell.firebaseapp.com',
    storageBucket: 'diagnosticos-fritzcell.firebasestorage.app',
  );
}
